spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:C:/data/recipe # Storing datas in file, for inmemory : jdbc:h2:mem:recipedb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    #generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  sql:
    init:
      mode: always