spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:/data/recipe # Storing datas in file, for inmemory : jdbc:h2:mem:recipedb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true